source 'https://rubygems.org'

gem 'rails', '3.2.10'
gem 'dicer', path: '../..'

gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'generator_spec'
  gem 'fakefs', require: 'fakefs/safe'

  gem 'factory_girl_rails'
  gem 'database_cleaner'
end
