source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'dicer', path: '../..'

gem 'sqlite3'

gem 'bcrypt-ruby', '~> 3.0.0', require: 'bcrypt'
gem 'slim-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'

  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'forgery'
  gem 'timecop'
end

group :development do
  gem 'pry-rails'
end
